name: 'Setup'
description: 'Set Python and NPM'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          npm install -g aws-cdk
          poetry install