name: Deploy Data Platform to Development

on:
  push:
    branches:
      - main
      - develop-**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Setup
        uses: ./.github/actions/setup

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}